# Generated by Django 4.2.1 on 2023-05-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharterLoanOptions',
        ),
        migrations.DeleteModel(
            name='CharterLoanProducts',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyOptions',
        ),
        migrations.DeleteModel(
            name='MortgageLoanOptions',
        ),
        migrations.DeleteModel(
            name='MortgageLoanProducts',
        ),
        migrations.DeleteModel(
            name='PersonalCreditLoanOptions',
        ),
        migrations.DeleteModel(
            name='PersonalCreditLoanProducts',
        ),
        migrations.DeleteModel(
            name='PersonSavingOptions',
        ),
        migrations.DeleteModel(
            name='PersonSavingProducts',
        ),
    ]
