# Generated by Django 4.2.1 on 2023-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField(unique=True)),
                ('cur_nm', models.TextField()),
                ('deal_bas_r', models.TextField()),
                ('dataDate', models.TextField(blank=True)),
            ],
        ),
    ]
